#!/usr/bin/env python3
"""Render README.md, TIMELINE.md and BY_INSTITUTION.md from data/papers.yaml.

    python scripts/generate_readme.py

These three files are build artifacts: any manual edit is overwritten on the
next run. Edit data/papers.yaml or data/categories.yaml instead.
"""

from __future__ import annotations

import datetime as dt
import re
from collections import Counter, defaultdict
from typing import Any

import common

BANNER = "<!-- Generated by scripts/generate_readme.py -- do not edit by hand. -->"


def github_anchor(heading: str, seen: dict[str, int] | None = None) -> str:
    """Reproduce GitHub's heading anchors, including its -1/-2 dedup suffixes."""
    text = heading.strip().lower()
    text = re.sub(r"[^\w\s-]", "", text)
    anchor = re.sub(r"\s", "-", text)
    if seen is None:
        return anchor
    count = seen.get(anchor, 0)
    seen[anchor] = count + 1
    return anchor if count == 0 else f"{anchor}-{count}"


def escape_cell(text: str) -> str:
    return str(text).replace("|", r"\|").replace("\n", " ")


def paper_cell(paper: dict[str, Any], show_summary: bool) -> str:
    title = escape_cell(paper.get("title") or paper.get("arxiv") or "Untitled")
    star = "⭐ " if paper.get("star") else ""
    cell = f"{star}**{title}**"
    summary = paper.get("summary")
    if show_summary and summary:
        cell += f"<br><sub>{escape_cell(summary)}</sub>"
    return cell


def links_cell(paper: dict[str, Any]) -> str:
    links = []
    url = paper.get("url") or (
        f"https://arxiv.org/abs/{paper['arxiv']}" if paper.get("arxiv") else None
    )
    if url:
        links.append(f"[Paper]({url})")
    if paper.get("code"):
        links.append(f"[Code]({paper['code']})")
    if paper.get("project"):
        links.append(f"[Project]({paper['project']})")
    return " · ".join(links) or "—"


def paper_table(papers: list[dict[str, Any]], today: dt.date, show_summary: bool) -> list[str]:
    lines = [
        "| Paper | Institution | Date | Links |",
        "| --- | --- | --- | --- |",
    ]
    for paper in papers:
        lines.append(
            f"| {paper_cell(paper, show_summary)} "
            f"| {escape_cell(paper.get('institution') or '—')} "
            f"| {common.date_badge(paper.get('date'), today)} "
            f"| {links_cell(paper)} |"
        )
    return lines


def sort_by_date(papers: list[dict[str, Any]]) -> list[dict[str, Any]]:
    return sorted(
        papers,
        key=lambda p: (common.parse_date(p.get("date")) or dt.date(1970, 1, 1), p.get("title") or ""),
        reverse=True,
    )


# --------------------------------------------------------------------------
# README
# --------------------------------------------------------------------------
def build_readme(categories: dict[str, Any], papers: list[dict[str, Any]], today: dt.date) -> str:
    meta = categories["meta"]
    show_summary = bool(meta.get("show_summary", True))
    repo = meta.get("repo", "")

    by_section: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for paper in papers:
        by_section[paper.get("section")].append(paper)

    counts = " · ".join(
        f"**{s['short']}: {len(by_section.get(s['id'], []))}**" for s in categories["sections"]
    )

    out: list[str] = [BANNER, "", f"# {meta['title']}", ""]
    out.append(
        "[![Awesome](https://awesome.re/badge-flat2.svg)](https://awesome.re) "
        f"![Papers](https://img.shields.io/badge/papers-{len(papers)}-blue?style=flat-square) "
        f"![Updated](https://img.shields.io/badge/updated-{today.isoformat().replace('-', '--')}-brightgreen?style=flat-square) "
        f"![License](https://img.shields.io/badge/license-{meta.get('license', 'CC0').replace(' ', '_').replace('-', '--')}-lightgrey?style=flat-square)"
    )
    out += ["", f"> {meta['subtitle'].strip()}", ""]
    out.append(f"**{len(papers)} papers** · {counts} · Last updated: **{today.isoformat()}**")
    out += [
        "",
        "📡 **[Daily arXiv feed](daily/)** — refreshed every morning with new papers "
        "matched against the taxonomy below.",
        "",
        "Other views: **[Timeline](TIMELINE.md)** · **[By institution](BY_INSTITUTION.md)** · "
        "**[Workflow](WORKFLOW.md)** · **[Contributing](CONTRIBUTING.md)**",
        "",
        "⭐ marks papers worth reading first if you are new to the area.",
        "",
        "---",
        "",
        "## Table of Contents",
        "",
    ]

    # Anchors are assigned in document order so the dedup suffixes GitHub adds
    # for repeated headings (three "Surveys" sections) stay in sync.
    seen_anchors: dict[str, int] = {}
    for heading in (meta["title"], "Table of Contents", "Latest Additions"):
        github_anchor(heading, seen_anchors)

    layout = []
    for section in categories["sections"]:
        section_heading = f"{section['numeral']}. {section['title']}"
        section_papers = by_section.get(section["id"], [])
        subs = []
        section_anchor = github_anchor(section_heading, seen_anchors)
        for sub in section["subcategories"]:
            sub_papers = [p for p in section_papers if p.get("subcategory") == sub["id"]]
            if not sub_papers:
                continue
            heading = f"{sub['title']} ({len(sub_papers)})"
            subs.append((sub, heading, github_anchor(heading, seen_anchors), sub_papers))
        layout.append((section, section_heading, section_anchor, section_papers, subs))

    for section, section_heading, section_anchor, section_papers, subs in layout:
        out.append(
            f"- [{section_heading}](#{section_anchor}) "
            f"（{section['title_zh']}, {len(section_papers)}）"
        )
        for sub, _heading, anchor, sub_papers in subs:
            out.append(f"  - [{sub['title']}](#{anchor}) ({len(sub_papers)})")
    out += ["", "---", ""]

    recent = sort_by_date(papers)[:10]
    out += ["## Latest Additions", ""]
    out += paper_table(recent, today, show_summary=False)
    out += ["", "---", ""]

    for section, section_heading, _anchor, _section_papers, subs in layout:
        out.append(f"## {section_heading}")
        out += ["", f"*{section['title_zh']} — {section['description'].strip()}*", ""]
        for _sub, heading, _sub_anchor, sub_papers in subs:
            out.append(f"### {heading}")
            out.append("")
            out += paper_table(sort_by_date(sub_papers), today, show_summary)
            out.append("")
        out += ["---", ""]

    out += [
        "## Contributing",
        "",
        "Add an entry to `data/papers.yaml` — the arXiv id, the category and one line of",
        "context are enough, the rest is filled in automatically:",
        "",
        "```yaml",
        '  - arxiv: "2410.24164"',
        '    institution: "Physical Intelligence"',
        "    section: vla            # llm | vlm | vla",
        "    subcategory: robot-arch # see data/categories.yaml",
        '    summary: "One line on why this paper matters."',
        "```",
        "",
        "Then run:",
        "",
        "```bash",
        "python scripts/add_paper.py 2410.24164   # or edit the YAML directly",
        "python scripts/sync_metadata.py          # pull title / date from arXiv",
        "python scripts/generate_readme.py        # regenerate the three views",
        "```",
        "",
        f"See [WORKFLOW.md](WORKFLOW.md) for how the daily automation works.",
        "",
        "## License",
        "",
        f"{meta.get('license', 'CC0 1.0')} — the paper metadata in this repository is free to reuse.",
        "",
    ]
    if repo:
        out += [f"<sub>Generated from `data/papers.yaml` · [{repo}](https://github.com/{repo})</sub>", ""]
    return "\n".join(out)


# --------------------------------------------------------------------------
# TIMELINE
# --------------------------------------------------------------------------
def build_timeline(categories: dict[str, Any], papers: list[dict[str, Any]], today: dt.date) -> str:
    labels = {s["id"]: s["short"] for s in categories["sections"]}
    sub_titles = {
        (s["id"], sub["id"]): sub["title"]
        for s in categories["sections"]
        for sub in s["subcategories"]
    }

    by_month: dict[str, list[dict[str, Any]]] = defaultdict(list)
    undated: list[dict[str, Any]] = []
    for paper in papers:
        date = common.parse_date(paper.get("date"))
        if date is None:
            undated.append(paper)
        else:
            by_month[date.strftime("%Y-%m")].append(paper)

    out = [
        BANNER,
        "",
        "# Timeline",
        "",
        f"All {len(papers)} papers in reverse chronological order (arXiv v1 date). "
        "Back to the [README](README.md).",
        "",
    ]
    for month in sorted(by_month, reverse=True):
        month_papers = sort_by_date(by_month[month])
        label = dt.datetime.strptime(month, "%Y-%m").strftime("%B %Y")
        out += [f"## {label} ({len(month_papers)})", ""]
        out += ["| Date | Paper | Track | Institution |", "| --- | --- | --- | --- |"]
        for paper in month_papers:
            track = labels.get(paper.get("section"), "?")
            sub = sub_titles.get((paper.get("section"), paper.get("subcategory")), "")
            url = paper.get("url") or f"https://arxiv.org/abs/{paper.get('arxiv')}"
            star = "⭐ " if paper.get("star") else ""
            out.append(
                f"| {common.format_date(paper.get('date'))} "
                f"| {star}[{escape_cell(paper.get('title', ''))}]({url}) "
                f"| `{track}` / {sub} "
                f"| {escape_cell(paper.get('institution') or '—')} |"
            )
        out.append("")

    if undated:
        out += ["## Undated", ""]
        out += paper_table(undated, today, show_summary=False)
        out.append("")
    return "\n".join(out)


# --------------------------------------------------------------------------
# BY_INSTITUTION
# --------------------------------------------------------------------------
def split_institutions(value: str, aliases: dict[str, str] | None = None) -> list[str]:
    """Split a comma-separated affiliation string and canonicalize each name."""
    if not value or value == "—":
        return []
    aliases = aliases or {}
    parts = re.split(r",| and (?=[A-Z0-9])", value)
    cleaned = []
    for part in parts:
        part = part.strip(" .")
        # Drop filler like "and 30+ institutions".
        if not part or re.fullmatch(r"\d+\+? institutions?", part, re.I):
            continue
        canonical = aliases.get(part, part)
        if canonical not in cleaned:
            cleaned.append(canonical)
    return cleaned


def build_by_institution(
    categories: dict[str, Any], papers: list[dict[str, Any]], today: dt.date
) -> str:
    labels = {s["id"]: s["short"] for s in categories["sections"]}
    aliases = categories.get("institution_aliases") or {}
    by_inst: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for paper in papers:
        for inst in split_institutions(paper.get("institution", ""), aliases):
            by_inst[inst].append(paper)

    ranked = sorted(by_inst.items(), key=lambda kv: (-len(kv[1]), kv[0].lower()))

    out = [
        BANNER,
        "",
        "# By Institution",
        "",
        f"{len(ranked)} institutions across {len(papers)} papers. A paper with several "
        "affiliations is counted under each of them. Back to the [README](README.md).",
        "",
        "## Leaderboard",
        "",
        "| # | Institution | Papers | LLM | VLM | VLA |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for rank, (inst, inst_papers) in enumerate(ranked[:25], start=1):
        tally = Counter(p.get("section") for p in inst_papers)
        out.append(
            f"| {rank} | [{inst}](#{github_anchor(inst)}) | {len(inst_papers)} "
            f"| {tally.get('llm', 0)} | {tally.get('vlm', 0)} | {tally.get('vla', 0)} |"
        )
    out += ["", "---", ""]

    for inst, inst_papers in ranked:
        out += [f"## {inst}", "", f"{len(inst_papers)} paper(s)", ""]
        out += ["| Date | Paper | Track |", "| --- | --- | --- |"]
        for paper in sort_by_date(inst_papers):
            url = paper.get("url") or f"https://arxiv.org/abs/{paper.get('arxiv')}"
            star = "⭐ " if paper.get("star") else ""
            out.append(
                f"| {common.format_date(paper.get('date'))} "
                f"| {star}[{escape_cell(paper.get('title', ''))}]({url}) "
                f"| `{labels.get(paper.get('section'), '?')}` |"
            )
        out.append("")
    return "\n".join(out)


def main() -> int:
    categories = common.load_categories()
    papers = common.load_papers()
    today = dt.date.today()

    (common.ROOT / "README.md").write_text(
        build_readme(categories, papers, today), encoding="utf-8"
    )
    (common.ROOT / "TIMELINE.md").write_text(
        build_timeline(categories, papers, today), encoding="utf-8"
    )
    (common.ROOT / "BY_INSTITUTION.md").write_text(
        build_by_institution(categories, papers, today), encoding="utf-8"
    )

    tally = Counter(p.get("section") for p in papers)
    print(f"Rendered {len(papers)} papers: " + ", ".join(f"{k}={v}" for k, v in sorted(tally.items())))
    print("  README.md, TIMELINE.md, BY_INSTITUTION.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
